version: "3.8"

# ==========================================================================
# PRODUCTION TESTING CONFIGURATION
# ==========================================================================
# Use this for production testing against your production domain
# Configure URLs via environment variables or GitHub secrets
# Commands:
#   docker-compose -f docker-compose.prod.yml up smoke-tests
#   docker-compose -f docker-compose.prod.yml up e2e-tests
#   docker-compose -f docker-compose.prod.yml --profile regression up regression-tests
#   docker-compose -f docker-compose.prod.yml --profile api up api-tests
# ==========================================================================

services:
  # Main E2E Tests - Full production test suite
  e2e-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    init: true
    ipc: host
    volumes:
      - ./test-results:/home/pwuser/app/test-results
      - ./playwright-report:/home/pwuser/app/playwright-report
    environment:
      - TARGET=prod
      - TEST_BASE_URL_PROD=${TEST_BASE_URL_PROD}
      - API_BASE_URL_PROD=${API_BASE_URL_PROD}
    networks:
      - e2e-prod-network
    command: npm run test
    restart: "no"

  # Critical Path Smoke Tests
  smoke-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: ci
    init: true
    ipc: host
    volumes:
      - ./test-results:/home/pwuser/app/test-results
      - ./playwright-report:/home/pwuser/app/playwright-report
    environment:
      - TARGET=prod
      - TEST_BASE_URL_PROD=${TEST_BASE_URL_PROD}
      - API_BASE_URL_PROD=${API_BASE_URL_PROD}
    networks:
      - e2e-prod-network
    command: npm run test:smoke
    restart: "no"

  # Comprehensive Regression Tests (use with --profile regression)
  regression-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    init: true
    ipc: host
    volumes:
      - ./test-results:/home/pwuser/app/test-results
      - ./playwright-report:/home/pwuser/app/playwright-report
    environment:
      - TARGET=prod
      - TEST_BASE_URL_PROD=${TEST_BASE_URL_PROD}
      - API_BASE_URL_PROD=${API_BASE_URL_PROD}
    networks:
      - e2e-prod-network
    command: npm run test:regression
    restart: "no"
    profiles:
      - regression

  # API-Only Tests (use with --profile api)
  api-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: ci
    init: true
    ipc: host
    volumes:
      - ./test-results:/home/pwuser/app/test-results
    environment:
      - TARGET=prod
      - API_BASE_URL_PROD=${API_BASE_URL_PROD}
    networks:
      - e2e-prod-network
    command: npm run test:api
    restart: "no"
    profiles:
      - api

networks:
  e2e-prod-network:
    driver: bridge

volumes:
  test-results:
    driver: local
