version: "3.8"

# ==========================================================================
# LOCALHOST/DEVELOPMENT TESTING CONFIGURATION
# ==========================================================================
# Use this for local development testing against localhost:3000
# Commands:
#   docker-compose -f docker-compose.dev.yml up e2e-tests
#   docker-compose -f docker-compose.dev.yml up smoke-tests
#   docker-compose -f docker-compose.dev.yml --profile debug up dev-runner
#   docker-compose -f docker-compose.dev.yml --profile codegen up codegen
# ==========================================================================

services:
  # Main E2E Tests - Full test suite against localhost
  e2e-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    init: true
    ipc: host
    volumes:
      - ./test-results:/home/pwuser/app/test-results
      - ./playwright-report:/home/pwuser/app/playwright-report
    environment:
      - TARGET=local
      - TEST_BASE_URL_LOCAL=http://host.docker.internal:3000
      - API_BASE_URL_LOCAL=http://host.docker.internal:3001/api
    networks:
      - e2e-dev-network
    command: npm run test

  # Quick Smoke Tests - Fast validation (Desktop Chrome only)
  smoke-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    init: true
    ipc: host
    volumes:
      - ./test-results:/home/pwuser/app/test-results
      - ./playwright-report:/home/pwuser/app/playwright-report
    environment:
      - TARGET=local
      - TEST_BASE_URL_LOCAL=http://host.docker.internal:3000
      - API_BASE_URL_LOCAL=http://host.docker.internal:3001/api
    networks:
      - e2e-dev-network
    command: npm run test:smoke

  # Interactive Debug Runner (use with --profile debug)
  dev-runner:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    init: true
    ipc: host
    volumes:
      - ./test-results:/home/pwuser/app/test-results
      - ./playwright-report:/home/pwuser/app/playwright-report
    environment:
      - TARGET=local
      - TEST_BASE_URL_LOCAL=http://host.docker.internal:3000
    networks:
      - e2e-dev-network
    command: npm run test:debug
    profiles:
      - debug

  # Code Generator (use with --profile codegen)
  codegen:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    init: true
    ipc: host
    volumes:
      - .:/home/pwuser/app
    environment:
      - TARGET=local
      - TEST_BASE_URL_LOCAL=http://host.docker.internal:3000
    networks:
      - e2e-dev-network
    command: npm run codegen:local
    profiles:
      - codegen

networks:
  e2e-dev-network:
    driver: bridge

volumes:
  test-results:
    driver: local
